from os import system
import time

ini = time.time()
print('--- PRE-TRAIN SVD ---')
system('python3 pretrain.py')
print('--- EXPERIMENTO UEX ---')
system('python3 uex.py')
print('Borramos datos usados ...')
system('rm -r datasets/UEX_Parkinson_ds/A/aug')
system('rm -r datasets/PCG_Parkinson_ds/A/aug')
print('--- EXPERIMENTO MIXED ---')
system('python3 mixed.py')
print('Borramos datos usados ...')
system('rm -r datasets/UEX_Parkinson_ds/A/aug')
system('rm -r datasets/PCG_Parkinson_ds/A/aug')
print('--- EXPERIMENTO CROSS1 ---')
system('python3 cross1.py')
print('Borramos datos usados ...')
system('rm -r datasets/UEX_Parkinson_ds/A/aug')
system('rm -r datasets/PCG_Parkinson_ds/A/aug')
print('--- EXPERIMENTO CROSS2 ---')
system('python3 cross2.py')
print('Borramos datos usados ...')
system('rm -r datasets/UEX_Parkinson_ds/A/aug')
system('rm -r datasets/PCG_Parkinson_ds/A/aug')
print('--- EXPERIMENTO PCG ---')
system('python3 pcg.py')
print('--- FIN DE LOS EXPERIMENTOS ---')
fin = time.time()
tot = (fin-ini)/60
print(f'--- TIEMPO TOTAL: {tot} MINUTOS ---')
